# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'taxidriverapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for taxidriverapp

  pod 'GoogleMaps'
  pod 'GooglePlaces'

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'React', :path => '../node_modules/react-native'
  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

end

